collections:
  #Collection mongodb from galaxy version 1.5.1 (latest as per this writing) has a bug for AlmaLinux.
  #It sets processManagement.Fork=true and that makes the service to not start. Look the template in the collection roles/mongodb_mongod/templates/mongod.conf.j2
  #https://www.mongodb.com/docs/manual/reference/configuration-options/#mongodb-setting-processManagement.fork
  - name: git+https://github.com/ansible-collections/community.mongodb
    version: master
    scm: git
    
  - ansible.posix

