---
#Some refs:
#https://github.com/ansible-collections/community.mongodb/issues/447
- name: Install and configure MongoDB on all nodes
  hosts: mongodb
  become: true
  pre_tasks:
    - name: yum | Install some useful packages
      ansible.builtin.yum:
        name:
          - bash-completion
          - vim
          - mlocate
          - python3-pip

    #https://checkmk.com/werk/14835
    #module mongodb_replicaset gives 'Unknown option directConnection' error with pymongo 3.7.0 (from yum).
    - name: Install pymongo
      ansible.builtin.pip:
        name: pymongo
        state: present

    - name: selinux | Disable SELlinux for now
      ansible.posix.selinux:
        state: permissive
        policy: targeted

    - name: Add MongoDB nodes to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ item }}"
      loop: "{{ groups['mongodb'] }}"

  roles:
    - role: community.mongodb.mongodb_repository
      tags: repository
  
    - role: community.mongodb.mongodb_linux
      tags: os_tuning
  
    - role: community.mongodb.mongodb_install
      tags: packages

    - role: community.mongodb.mongodb_mongod
      tags: [config, replicaset]

#  tasks:
#    - name: service | Start mongod service
#      ansible.builtin.service:
#        name: mongod
#        state: started
#        enabled: true
  
- name: Configure mongod service for replication
  hosts: mongodb
  become: true
  roles:

  tasks:
  - name: replica_set | Initialize MongoDB replica set
    tags: replicaset
    any_errors_fatal: true
    community.mongodb.mongodb_replicaset:
      replica_set: "rs0"
      members: '{{ groups.mongodb }}'
      arbiter_at_index: 2
      debug: true
    when: groups.mongodb.index(inventory_hostname) == 0
